# Generated by Django 5.1.5 on 2025-02-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Подписка"),
        ),
    ]
